### ISSUE TITLE
'Authenticate' non funziona.

### ISSUE THREAD

**Issue by zFelixYT** [sever89-dev/BUUIDPicker#1]
Inserendo il mio nickname e facendo authenticate mi da un errore ed io non posso loggarmi nel launcher SP. Perfavore fixate.

**Comment by sever89-dev** [comment]
Perfetto, grazie per la segnalazione.. Provvederò a fixare nella nuova versione 1.1.1
Grazie ancora - @sever89-dev (@BlackGriefingOfficial)
